---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;border:none}
.tg td{overflow:hidden;word-break:normal}
.tg th{overflow:hidden;word-break:normal}
.tg .tg-9hbo{font-weight:bold;vertical-align:top}
.tg .tg-yw4l{vertical-align:top;text-align:left}
.tg .tg-yw4i{vertical-align:top;text-align:left;font-style:italic}
</style>
<table class="tg">
<col width="130">
  <tr>
    <td class="tg-9hbo">10.2013 - present</td>
    <td class="tg-yw4i">Uniwersytet Przyrodniczy w Poznaniu - adiunkt</td>
  </tr>
  <tr>
    <td class="tg-yw4l"></td>
    <td class="tg-yw4l">Badania naukowe z zakresu biostatystyki i bioinformatyki. W szczególności rozwijanie metod statystycznych stosowanych w analizie różnicowej danych pochodzących z sekwencjonowania nowej generacji.<br>
Prowadzenie zajęć - Matematyka z elementami algebra, Podstawy statystyki, Technologie informacyjne. </td>
  </tr>
  <tr>
    <td class="tg-9hbo">06.2014 - 07.2014</td>	
    <td class="tg-yw4i">College of William and Mary - mentor podczas Research Experience for Undergraduate Students</td>
  </tr>  
  <tr>
    <td class="tg-yw4l"></td>
    <td class="tg-yw4l">Badania naukowe z zakresu matematyki, głównie dotyczące algebra liniowej i macierzowej oraz teorii grafów. W szczególności praca nad uzupełnianiem macierzy typu TP (totally positive) oraz praca nad listami wartości własnych macierzy reprezentowanych za pomocą drzew.</td>
  </tr>
  <tr>
    <td class="tg-9hbo">06.2012 - 06.2013</td>	
    <td class="tg-yw4i">Functional Genomics Center Zurich - staż naukowy w ramach grantu (nr 11.182) Programu wymiany naukowej między Szwajcarią a nowymi państwami członkowskimi Unii Europejskiej Sciex-NMSch;</td>
  </tr>  
  <tr>
    <td class="tg-yw4l"></td>
    <td class="tg-yw4l">Projekt dotyczący statystycznych analiz pozwalających na wykrywanie i badanie takich zjawisk, jak alternatywny splicing, zatrzymywane introny i mostki eksonowe; praca na platformach Illumina HiSeq 2000, SOLiD GX 5500, PacBio.</td>
  </tr>
  <tr>
    <td class="tg-9hbo">10.2009 - 09.2013</td>	
    <td class="tg-yw4i">Uniwersytet Przyrodniczy w Poznaniu - doktorant;</td>
  </tr>  
  <tr>
    <td class="tg-yw4l"></td>
    <td class="tg-yw4l">Prowadzenie ćwiczeń do przedmiotów "Matematyka z elementami statystyki", "Matematyka" i "Technologie informacyjne"</td>
  </tr>
  <tr>
    <td class="tg-9hbo">09.2008 - 12.2008</td>	
    <td class="tg-yw4i">SNS Reaal, Dział Zarządzania Ryzykiem, Utrecht, Holandia - staż w ramach programu Lifelong Learning Programme Erasmus;</td>
  </tr>  
  <tr>
    <td class="tg-yw4l"></td>
    <td class="tg-yw4l">Projekt dotyczący zastosowań kopuł do problemów związanych z zarządzaniem ryzykiem, w szczególności do obliczania Kapitału Ekonomicznego firmy.</td>
  </tr>
</table>
