---
title: "Publications"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



+ Szenajch, J., Szabelska-Beręsewicz, A., Świercz, A., Zyprych-Walczak, J., Siatkowski, I., Góralski, M., Synowiec, A., & Handschuh, L. (2020). Transcriptome Remodeling in Gradual Development of Inverse Resistance between Paclitaxel and Cisplatin in Ovarian Cancer Cells. *International journal of molecular sciences*, 21(23), 9218, doi: https://doi.org/10.3390/ijms21239218. [IF = 4.556]
+ Johnson C. R., Lettie J., Mack-Crane S., Szabelska-Beręsewicz A. (2020). Branch duplication in trees: uniqueness of seeds and enumeration of seeds. *Proyecciones (Antofagasta, On line)*, 39(2), 451-465, doi: https://doi.org/10.22199/issn.0717-6279-2020-02-0028.
+ Różańska-Zawieja J., Szabelska-Beręsewicz A., Sobek Z., Zyprych-Walczak J., Siatkowski I. (2019). Assessment of heritability coefficient variation for various breeds of cattle. *Journal of Animal & Plant Sciences*, 39(1), 6351-6358.[IF = 0.529]
+ Szabelska-Beręsewicz A., Jakubus M., Siatkowski I. (2018). Multivariate analysis used for evaluation of the bioavailability of heavy metals in various composts. *Nauka Przyroda Technologia*, 12(2), 221-235, doi: http://dx.doi.org/10.17306/J.NPT.00244.
+ Leśniewska A., Zyprych-Walczak J., Szabelska-Beręsewicz A., Okoniewski M. J. (2018). Genes sharing the protein family domain decrease the performance of classification with RNA-seq genomic signatures. *Biology Direct*, 13 (1), 3, doi: 10.1186/s13062-018-0205-x. [IF = 2.856]
+ Anjanappa R. B., Mehta D., Okoniewski M. J., Szabelska-Beręsewicz A., Gruissem W., Vanderschuren H. (2018). Molecular insights into Cassava brown streak virus susceptibility and resistance by profiling of the early host response. *Molecular Plant Pathology*, 19(2), 476-489, doi: 10.1111/mpp.12565.[IF = 4.697]
+ Różańska-Zawieja J., Szabelska-Beręsewicz A., Sobek Z., Nienartowicz-Zdrojewska A., Zyprych-Walczak J., Siatkowski I., (2017). Wpływ wielkości grup ojcowskich i stad na optymalną ocenę współczynnika odziedziczalności długości ciąży u bydła. *Roczniki Naukowe Polskiego Towarzystwa Zootechnicznego*, 13 (1), 9-17.
+ Beręsewicz M., Alvarez A., Biecek P., Dyderski M. K., Kosiński M., Nowosad J., Rotter K., Szabelska-Beręsewicz A., Szymkowiak M., Wawrowski Ł., Zyprych-Walczak J. (2017). Conference Report: European R Users Meeting 2016. *The R Journal*, 9 (1), 501-504.
+ Szabelska-Beręsewicz, A., Bilska A., Waszkowiak K., Siatkowski I., (2016). A note on the comparison of mixed-effects models for longitudinal studies. *Biometrical Letters* 53 (2), 165-173.
+	Szenajch J., Góralski M., Świercz A., Szabelska A., Zyprych-Walczak J., Synowiec A., Siatkowski I., Handschuh L. (2016). Zmiany w ekspresji szlaków sygnałowych uczestniczące w wykształcaniu nabytej w obecności erytropoetyny oporności na ci-splatynę i paklitaksel w komórkach ludzkiego raka jajnika. Nowotwory, vol. 66, suppl. 2, p. 50.
+ Wiewiorka M. S., Szabelska A.,  Okoniewski M. J., (2015). Analysis of AmpliSeq RNA-sequencing enrichment panels. In: Kryszkiewicz, M., Bandyopadhyay, S., Rybinski, H., Pal, S.K. (red.), Pattern Recognition and Machine Intelligence, 495-500. Warszawa: Springer International Publishing; doi: 10.1007/978-3-319-19941-2_47
+ Zyprych-Walczak J., Szabelska A., Handschuh L., Gorczak K., Klamecka K., Figlerowicz M., Siatkowski I., (2015). The impact of normalization methods on RNA-seq data analysis. *BioMed Research International*, Article ID 621690; doi: 10.1155/2015/621690.
+ Gorczak K., Klamecka K., Szabelska A., Zyprych-Walczak J., Siatkowski I., (2014). Graphical methods for differential analysis of RNA-Seq data. *Colloquium Biometricum* 44, 167-181.
+ Szabelska A., Wiewiorka M., Okoniewski M. J., (2013). ampliQueso: Analysis of amplicon enrichment panels. Reviewed R package, Bioconductor: http://www.bioconductor.org/packages/release/bioc/html/ampliQueso.html
+ Uszczynska B., Zyprych-Walczak J., Handschuh L., Szabelska A., Kazmierczak M., Woronowicz W., Kozlowski P., Sikorski M. M., Komarnicki M., Siatkowski I., Figlerowicz M., (2013). Analysis of boutique arrays: A universal method for the selection of the optimal data normalization procedure. *International Journal of Molecular Medicine*, 32 (3), 668-684. [IF = 1.957]
+ Tomkowiak A., Weigt D., Broda Z., Mikolajczyk S., Szabelska A., Zyprych J., Siatkowski I., (2013). Analysis of relationship between genetic and phenotypic similarity of alfaalfa mutants inflorescences. *Nauka Przyroda Technologia* 7 (3) #34.
+ Okoniewski M. J., Meienberg J., Patrignani A., Szabelska A., Matyas G., Schlapbach R., (2013). Precise breakingpoint localization of large genomic deletions using PacBio and Illumina next generation sequencers.  Method summary. *Biotechniques*, 54 (2), 98-100. [IF = 2.669]
+ Szabelska A., Zyprych-Walczak J., Siatkowski I., (2012). Application of linear mixed models in the selection of genes from microarray experiments with repeated measurements.  *Colloquium Biometricum* 42, 103-109.
+ Okoniewski M. J., Lesniewska A., Szabelska A., Zyprych-Walczak J., Ryan M., Wachtel M., Morzy T., Schaeffer B., Schlapbach R., (2011). Preferred analysis methods for single genomic regions in RNA sequencing revealed by processing the shape of coverage. *Nucleic Acids Research*, doi: 10.1093/nar/gkr1249. [IF = 8.055]
+ Schmidt M., L. Handschuh,  Zyprych J., Szabelska A., Olejnik-Schmidt A., Siatkowski I., Figlerowicz M., (2011). Impact of DNA microarray data transformation on gene expression analysis - comparison of two normalization method. *Acta Biochimica Polonica* 58 (4), 573-580. [IF = 1.234]
+ Piekarska-Boniecka H., Siatkowski I., Szabelska A., (2011). The usefulness of similarity coefficients in the comparison of biocenosis structural units. *Nauka Przyroda Technologia*, 5 (6) # 111.
+ Zyprych-Walczak J., Szabelska A., Siatkowski I., (2011). Application of statistical tests in gene selection problems. *Biometrical Letters*, 48 (2), 113-121.
+ Waligora H., Weber A., Skrzypczak W., Szabelska A., (2011). Influence of weather conditions on damages of some types of sugar maize by frit fly (Oscinella frit L.). *Nauka Przyroda Technologia* 5 (2) #10.
+ Siatkowski M., Szabelska A., Zyprych J., Weres J., Kujawa S., (2010). Growth curve functions in modeling the thin-layer drying of corn. *Inżynieria Rolnicza* 6 (124).
+ Thornton A., Szabelska A., Zyprych J. et. al., (2010). Modelling and Optimization of Algae Growth. *Proceedings of the 72nd European Study Group - Mathematics with Industry*, 54-85.
+ Siatkowski I., Goszczurna T., Szabelska A., Zyprych J., (2010). Coefficients of dissimilarity and similarity with applications. *Colloquium Biometricum* 40, p.13-23.
+ Szabelska A., Siatkowski M., Goszczurna T., Zyprych J., (2010). Comparison of growth models in R. *Nauka Przyroda Technologia* 4 (4) #50.
