---
title: "Publications"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## 2024

+ Stachowiak, M., Nowacka-Woszuk, J., Szabelska-Beresewicz, A., Zyprych-Walczak, J., Krzeminska, P., Sosinski, O., ... & Switonski, M. (2024). A massive alteration of gene expression in undescended testicles of dogs and the association of KAT6A variants with cryptorchidism. *PNAS*, 121(7), e2312724121, doi: 10.1073/pnas.231272412
+ Wielkopolan, B., Szabelska‐Beręsewicz, A., Gawor, J., & Obrępalska‐Stęplowska, A. (2024). Cereal leaf beetle‐associated bacteria enhance the survival of their host upon insecticide treatments and respond differently to insecticides with different modes of action. *Environmental Microbiology Reports*, 16(2), e13247, doi: doi.org/10.1111/1758-2229.13247

## 2023

+ Szabelska-Beresewicz, A., Zyprych-Walczak, J. Siatkowski I, Okoniewski M. (2023) Ambiguous genes due to aligners and their impact on RNA-seq data analysis. *Sci Rep.* 8; 13(1), 21770, doi:  10.1038/s41598-023-41085-6
+ Jakubowska M, Dobosz R, Szabelska-Beręsewicz A, Zyprych-Walczak J, Kowalska J, Tratwal A. (2023) Effects of water-based extracts of peppermint (Mentha piperita L.) and French marigold (Tagetes patula L.) on the transformation of larvae and nymphs of two-spotted spider mite (Tetranychus urticae Koch). *Journal of Plant Protection Research*, 63(3), 474-480, doi: 10.24425/jppr.2023.147828 
+ Wertheim-Tysarowska, K., Osipowicz, K., Gielniewski, B., Wojtaś, B., Szabelska-Beręsewicz, A., Zyprych-Walczak, J., ... & Jezela-Stanek, A. (2023). The Epidermal Transcriptome Analysis of a Novel c. 639_642dup LORICRIN Variant-Delineation of the Loricrin Keratoderma Pathology. *Int. J. Mol. Sci.*, 24(11), 9459, doi: https://doi.org/10.3390/ijms24119459
+ Górna, A., Szabelska-Beręsewicz, A., Wieruszewski, M., Starosta-Grala, M., Stanula, Z., Kożuch, A., & Adamowicz, K. (2023). Predicting Post-Production Biomass Prices. *Energies*, 16(8), 3470, doi: https://doi.org/10.3390/en16083470

## 2022

+ Górna, A.; Wieruszewski, M.; Szabelska-Beręsewicz, A.; Stanula, Z.; Adamowicz, K. (2022) Biomass Price Prediction Based on the Example of Poland. *Forests*, 13, 2179, doi: https://doi.org/10.3390/f13122179
+ Krawczyk K., Szabelska-Beręsewicz A., Przemieniecki S.W., Szymańczyk M., Obrępalska-Stęplowska A. (2022) Insect Gut Bacteria Promoting the Growth of Tomato Plants (Solanum lycopersicum L.). *Int. J. Mol. Sci.*, 23, 13548, doi: https://doi.org/10.3390/ijms232113548
+ Nowacka-Woszuk J., Stachowiak M., Szczerbal I., Szydlowski M., Szabelska-Beręsewicz A., Zyprych-Walczak J., ... & Switonski M. (2022). Whole genome sequencing identifies a missense polymorphism in PADI6 associated with testicular/ovotesticular XX disorder of sex development in dogs. *Genomics*, 114(4), 110389, doi: https://doi.org/10.1016/j.ygeno.2022.110389
+ Sobek Z., Rozanska-Zawieja J., Siatkowski I., Szabelska-Beresewicz A., & Zyprych-Walczak J. (2022). Assessment of the accuracy of selected models used to estimate the heritability coefficient in a cattle population. *Animal Science and Genetics*, 18(1), doi: https://10.5604/01.3001.0015.7774
+ Niedziela, G., Szabelska-Beręsewicz, A., Zyprych-Walczak, J., Graczyk, M. (2022). Application of edgeR and DESeq2 methods in plant experiments based on RNA-seq technology. *Biometrical Letters* 59(2), 127-139, doi: https://doi.org/10.2478/bile-2022-0009

## 2021

+ Wielkopolan B., Krawczyk K., Szabelska-Beręsewicz A., Obrępalska-Stęplowska A. (2021). The structure of the cereal leaf beetle (Oulema melanopus) microbiome depends on the insect’s developmental stage, host plant, and origin. Scientific reports, 11(1), 1--19, doi: https://doi.org/10.1038/s41598-021-99411-9
+ Mikac S., Rychłowski M., Dziadosz A., Szabelska-Beresewicz A., Fahraeus R., Hupp T., Sznarkowska A. (2021). Identification of a Stable, Non-Canonically Regulated Nrf2 Form in Lung Cancer Cells. *Antioxidants*, 10(5), 786, doi: https://doi.org/10.3390/antiox10050786
+ Różańska-Zawieja J., Winnicki S., Zyprych-Walczak J., Szabelska-Beręsewicz A., Siatkowski I., Nowak W., Stefańska B., Kujawiak R., Sobek Z. (2021). The Effect of Feeding Management and Culling of Cows on the Lactation Curves and Milk Production of Primiparous Dairy Cows. *Animals*, 11(7), 1959, doi: https://doi.org/10.3390/ani11071959

## 2020

+ Szenajch J., Szabelska-Beręsewicz A., Świercz A., Zyprych-Walczak J., Siatkowski, I., Góralski M., Synowiec A. & Handschuh, L. (2020). Transcriptome Remodeling in Gradual Development of Inverse Resistance between Paclitaxel and Cisplatin in Ovarian Cancer Cells. *International journal of molecular sciences*, 21(23), 9218, doi: https://doi.org/10.3390/ijms21239218.
+ Johnson C. R., Lettie J., Mack-Crane S., Szabelska-Beręsewicz A. (2020). Branch duplication in trees: uniqueness of seeds and enumeration of seeds. *Proyecciones (Antofagasta, On line)*, 39(2), 451-465, doi: https://doi.org/10.22199/issn.0717-6279-2020-02-0028.

## 2019

+ Różańska-Zawieja J., Szabelska-Beręsewicz A., Sobek Z., Zyprych-Walczak J., Siatkowski I. (2019). Assessment of heritability coefficient variation for various breeds of cattle. *Journal of Animal & Plant Sciences*, 39(1), 6351-6358.

## 2018

+ Szabelska-Beręsewicz A., Jakubus M., Siatkowski I. (2018). Multivariate analysis used for evaluation of the bioavailability of heavy metals in various composts. *Nauka Przyroda Technologia*, 12(2), 221-235, doi: http://dx.doi.org/10.17306/J.NPT.00244.
+ Leśniewska A., Zyprych-Walczak J., Szabelska-Beręsewicz A., Okoniewski M. J. (2018). Genes sharing the protein family domain decrease the performance of classification with RNA-seq genomic signatures. *Biology Direct*, 13 (1), 3, doi: 10.1186/s13062-018-0205-x.

## 2017

+ Anjanappa R. B., Mehta D., Okoniewski M. J., Szabelska-Beręsewicz A., Gruissem W., Vanderschuren H. (2017). Molecular insights into Cassava brown streak virus susceptibility and resistance by profiling of the early host response. *Molecular Plant Pathology*, doi: 10.1111/mpp.12565.
+ Różańska-Zawieja J., Szabelska-Beręsewicz A., Sobek Z., Nienartowicz-Zdrojewska A., Zyprych-Walczak J., Siatkowski I., (2017). Wpływ wielkości grup ojcowskich i stad na optymalną ocenę współczynnika odziedziczalności długości ciąży u bydła. *Roczniki Naukowe Polskiego Towarzystwa Zootechnicznego*, 13 (1), 9-17.
+ Beręsewicz M., Alvarez A., Biecek P., Dyderski M. K., Kosiński M., Nowosad J., Rotter K., Szabelska-Beręsewicz A., Szymkowiak M., Wawrowski Ł., Zyprych-Walczak J. (2017). Conference Report: European R Users Meeting 2016. *The R Journal*, 9 (1), 501-504.

## 2016

+ Szabelska-Beręsewicz, A., Bilska A., Waszkowiak K., Siatkowski I., (2016). A note on the comparison of mixed-effects models for longitudinal studies. *Biometrical Letters* 53 (2), 165-173.
+	Szenajch J., Góralski M., Świercz A., Szabelska A., Zyprych-Walczak J., Synowiec A., Siatkowski I., Handschuh L. (2016). Zmiany w ekspresji szlaków sygnałowych uczestniczące w wykształcaniu nabytej w obecności erytropoetyny oporności na ci-splatynę i paklitaksel w komórkach ludzkiego raka jajnika. Nowotwory, vol. 66, suppl. 2, p. 50. 

## 2015

+ Wiewiorka M. S., Szabelska A.,  Okoniewski M. J., (2015). Analysis of AmpliSeq RNA-sequencing enrichment panels. In: Kryszkiewicz, M., Bandyopadhyay, S., Rybinski, H., Pal, S.K. (red.), Pattern Recognition and Machine Intelligence, 495-500. Warszawa: Springer International Publishing; doi: 10.1007/978-3-319-19941-2_47
+ Zyprych-Walczak J., Szabelska A., Handschuh L., Gorczak K., Klamecka K., Figlerowicz M., Siatkowski I., (2015). The impact of normalization methods on RNA-seq data analysis. *BioMed Research International*, Article ID 621690; doi: 10.1155/2015/621690.

## 2014

+ Gorczak K., Klamecka K., Szabelska A., Zyprych-Walczak J., Siatkowski I., (2014). Graphical methods for differential analysis of RNA-Seq data. *Colloquium Biometricum* 44, 167-181.
+ Szabelska A., Wiewiorka M., Okoniewski M. J., (2013). ampliQueso: Analysis of amplicon enrichment panels. Reviewed R package, Bioconductor: http://www.bioconductor.org/packages/release/bioc/html/ampliQueso.html

## 2013

+ Uszczynska B., Zyprych-Walczak J., Handschuh L., Szabelska A., Kazmierczak M., Woronowicz W., Kozlowski P., Sikorski M. M., Komarnicki M., Siatkowski I., Figlerowicz M., (2013). Analysis of boutique arrays: A universal method for the selection of the optimal data normalization procedure. *International Journal of Molecular Medicine*, 32 (3), 668-684.
+ Tomkowiak A., Weigt D., Broda Z., Mikolajczyk S., Szabelska A., Zyprych J., Siatkowski I., (2013). Analysis of relationship between genetic and phenotypic similarity of alfaalfa mutants inflorescences. *Nauka Przyr. Technol.* 7 (3) #34.
+ Okoniewski M. J., Meienberg J., Patrignani A., Szabelska A., Matyas G., Schlapbach R., (2013). Precise breakingpoint localization of large genomic deletions using PacBio and Illumina next generation sequencers.  Method summary. *Biotechniques*, 54 (2), 98-100.

## 2012

+ Szabelska A., Zyprych-Walczak J., Siatkowski I., (2012). Application of linear mixed models in the selection of genes from microarray experiments with repeated measurements.  *Colloquium Biometricum* 42, 103-109.

## 2011

+ Okoniewski M. J., Lesniewska A., Szabelska A., Zyprych-Walczak J., Ryan M., Wachtel M., Morzy T., Schaeffer B., Schlapbach R., (2011). Preferred analysis methods for single genomic regions in RNA sequencing revealed by processing the shape of coverage. *Nucleic Acids Research*, doi: 10.1093/nar/gkr1249.
+ Schmidt M., L. Handschuh,  Zyprych J., Szabelska A., Olejnik-Schmidt A., Siatkowski I., Figlerowicz M., (2011). Impact of DNA microarray data transformation on gene expression analysis - comparison of two normalization method. *Acta Biochimica Polonica* 58 (4), 573-580.
+ Piekarska-Boniecka H., Siatkowski I., Szabelska A., (2011). The usefulness of similarity coefficients in the comparison of biocenosis structural units. *Nauka Przyroda Technologia*, 5 (6) # 111.
+ Zyprych-Walczak J., Szabelska A., Siatkowski I., (2011). Application of statistical tests in gene selection problems. *Biometrical Letters*, 48 (2), 113-121.
+ Waligora H., Weber A., Skrzypczak W., Szabelska A., (2011). Influence of weather conditions on damages of some types of sugar maize by frit fly (Oscinella frit L.). *Nauka Przyroda Technologia* 5 (2) #10.
+ Siatkowski M., Szabelska A., Zyprych J., Weres J., Kujawa S., (2010). Growth curve functions in modeling the thin-layer drying of corn. *Inżynieria Rolnicza* 6 (124).

## 2010

+ Thornton A., Szabelska A., Zyprych J. et. al., (2010). Modelling and Optimization of Algae Growth. *Proceedings of the 72nd European Study Group - Mathematics with Industry*, 54-85.
+ Siatkowski I., Goszczurna T., Szabelska A., Zyprych J., (2010). Coefficients of dissimilarity and similarity with applications. *Colloquium Biometricum* 40, p.13-23.
+ Szabelska A., Siatkowski M., Goszczurna T., Zyprych J., (2010). Comparison of growth models in R. *Nauka Przyroda Technologia* 4 (4) #50.